version: '3'
services:
  php8:
      build:
          context: ./Docker/php8
      hostname: php8
      ports:
        - "9000:9000"
      volumes:
        - ./Projects/:/var/www/html/
        - ./Docker/php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - ./Docker/php8/php.ini:/usr/local/etc/php/php.ini
  php8.1:
    build:
      context: ./Docker/php8.1
    hostname: php8.1
    ports:
      - "9001:9000"
    volumes:
      - ./Projects/:/var/www/html/
      - ./Docker/php8.1/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./Docker/php8.1/php.ini:/usr/local/etc/php/php.ini
  nginx:
        platform: linux/x86_64
        image: nginx:1.13.8
        ports:
          - "80:80"
        volumes:
          - ./Projects/:/var/www/html/
          - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php8
          - php8.1